"""
Kronecker Graph.

Kronecker graphs are generated by recursive Kronecker products of a
small "initiator" matrix K₁.  After t iterations:

    K_t = K₁ ⊗ K₁ ⊗ ... ⊗ K₁   (t times)

yielding a graph on n = k^t nodes (where k is the size of K₁).

Each entry K_t[i, j] gives the probability of edge (i, j).  Edges
are sampled independently from these probabilities (stochastic
Kronecker graph).

The model can produce realistic network properties: heavy-tailed
degree distributions, community structure, densification, and
shrinking diameter.

Since k^t may not match the layout's n exactly, we sample from the
Kronecker matrix at the required size by taking the leading n×n
submatrix (or by interpolation).

Reference:
    Leskovec, J., Chakrabarti, D., Kleinberg, J., Faloutsos, C., &
    Ghahramani, Z. (2010). "Kronecker Graphs: An Approach to Modeling
    Networks." JMLR, 11, 985–1042.
"""

from __future__ import annotations

import networkx as nx
import numpy as np

from graphgallery.base import GraphBuilder, ParamInfo
from graphgallery.points import PointLayout


class KroneckerGraph(GraphBuilder):
    """Recursive Kronecker product graph with realistic properties.

    Parameters:
        initiator: 2D initiator matrix (default: 2×2 realistic).
        iterations: Number of Kronecker products (auto-set if None).
        seed: Random seed.
    """

    slug = "kronecker"
    category = "random_models"

    # Default initiator from the SNAP paper
    DEFAULT_INITIATOR = np.array([
        [0.9, 0.5],
        [0.5, 0.3],
    ])

    def __init__(
        self,
        initiator: np.ndarray | None = None,
        iterations: int | None = None,
        seed: int | None = None,
    ):
        self.initiator = (
            initiator if initiator is not None
            else self.DEFAULT_INITIATOR.copy()
        )
        self.iterations = iterations
        self.seed = seed

    @property
    def name(self) -> str:
        return "Kronecker Graph"

    @property
    def description(self) -> str:
        k = self.initiator.shape[0]
        return (
            f"Recursive Kronecker product of a {k}×{k} initiator matrix. "
            f"Produces realistic heavy-tailed networks."
        )

    @property
    def is_deterministic(self) -> bool:
        return False

    @property
    def is_spatial(self) -> bool:
        return False

    @property
    def complexity(self) -> str:
        return "O(n²) for probability matrix, O(E[m]) for sampling"

    def params_info(self) -> list[ParamInfo]:
        return [
            ParamInfo(
                "initiator",
                "k×k initiator probability matrix",
                "ndarray", "[[0.9,0.5],[0.5,0.3]]",
            ),
            ParamInfo(
                "iterations",
                "Kronecker product iterations (None=auto)",
                "int | None", None, "≥ 1",
            ),
            ParamInfo("seed", "Random seed", "int | None", None),
        ]

    def build(self, layout: PointLayout) -> nx.Graph:
        self.validate_layout(layout)
        n = layout.n_points
        k = self.initiator.shape[0]

        seed = self.seed if self.seed is not None else (layout.seed + 108)
        rng = np.random.default_rng(seed)

        # Determine iterations: k^t ≥ n
        if self.iterations is not None:
            t = self.iterations
        else:
            t = max(1, int(np.ceil(np.log(n) / np.log(k))))

        # Build the Kronecker probability matrix
        prob_matrix = self.initiator.copy()
        for _ in range(t - 1):
            prob_matrix = np.kron(prob_matrix, self.initiator)

        # Trim or pad to exactly n×n
        kron_n = prob_matrix.shape[0]
        if kron_n >= n:
            prob_matrix = prob_matrix[:n, :n]
        else:
            # Pad with small probabilities
            padded = np.full((n, n), 0.05)
            padded[:kron_n, :kron_n] = prob_matrix
            prob_matrix = padded

        # Ensure symmetry and clamp to [0, 1]
        prob_matrix = (prob_matrix + prob_matrix.T) / 2.0
        np.clip(prob_matrix, 0.0, 1.0, out=prob_matrix)
        np.fill_diagonal(prob_matrix, 0.0)  # No self-loops

        # Sample edges
        G = nx.Graph()
        G.add_nodes_from(range(n))

        uniform_draws = rng.random((n, n))
        for i in range(n):
            for j in range(i + 1, n):
                if uniform_draws[i, j] < prob_matrix[i, j]:
                    G.add_edge(i, j)

        G.graph["model"] = "kronecker"
        G.graph["initiator"] = self.initiator.tolist()
        G.graph["iterations"] = t

        return G
